### ISSUE TITLE
Broken links to WebCodecs Registration pages

### ISSUE THREAD

**Issue by juj** [w3c/webcodecs#365] opened 2021-09-24 07:10 UTC
In section 3. Audio Codec Registry, the links

<html>
<body>

flac | Flac | FLAC codec registration [WEBCODECS-FLAC-CODEC-REGISTRATION]
-- | -- | --
mp3 | MP3 | MP3 WebCodecs Registration [WEBCODECS-MP3-CODEC-REGISTRATION]
mp4a.* | AAC | AAC WebCodecs Registration [WEBCODECS-AAC-CODEC-REGISTRATION]
opus | Opus | Opus WebCodecs Registration [WEBCODECS-OPUS-CODEC-REGISTRATION]

</body>
</html>

each point to a HTTP 404 page.

**Comment by juj** [comment] 2021-09-24 07:14
On the same note, what are the supported codes for AAC?

The only link that works here is the `vorbis` codec, and it points to the start of the full spec that does not seem to speak anything about codec strings for WebCodecs? I hope once the HTTP 404 errors are resolved, that the links will point to a place where it is easy at a glance to see what the possible codec strings are for AAC (rather than link to the full AAC spec where one may need to dig up subsections of subsections to find the right info?)

I.e. a case of "I just want to decode AAC, I don't want to have to go through the full spec to do that".

**Comment by chrisn** [comment] 2021-09-24 07:36
We're working to update the registry links in https://github.com/w3c/webcodecs/issues/359. There's an [open PR](https://github.com/w3c/webcodecs/pull/364) for Vorbis. In the meantime, you can see the AAC registration [here](https://w3c.github.io/webcodecs/aac_codec_registration.html).

**Comment by chcunningham** [comment] 2021-09-24 17:39
Sorry for the breaks. To build on the point above, for now you can access any of the pages by performing the transformation like:

busted: https://www.w3.org/TR/webcodecs-aac-codec-registration/ 
working: https://w3c.github.io/webcodecs/aac_codec_registration.html

similarly

busted: https://www.w3.org/TR/webcodecs-vorbis-codec-registration/ 
working: https://w3c.github.io/webcodecs/vorbis_codec_registration.html

and so on.

**Comment by chcunningham** [comment] 2021-09-24 23:20
Closing as duplicate of #359

**Closed by chcunningham** 2021-09-24 23:20 UTC
