### ISSUE TITLE
Optional mimeType for ImageDecoder?

### ISSUE THREAD

**Issue by jakearchibald** [w3c/webcodecs#252] opened 2021-05-21 14:00 UTC
Right now, you need to provide a mimeType for `ImageDecoder`, but `createImageBitmap` uses sniffing.

Could the `ImageDecoder` mimetype be optional and use sniffing if one isn't provided?

**Comment by jakearchibald** [comment] 2021-05-21 14:03
Some more context: On squoosh.app we'd like to use `ImageDecoder`, particularly for animated file formats.

Right now `<img>` supports animated formats, even if the mime type is incorrect.

If we want to match the support of `<img>` where the file extension or mime type doesn't matter, but be able to grab particular frames from the animated format, we would need to implement our own sniffing, even though that code already exists in the browser.

**Comment by dalecurtis** [comment] 2021-05-21 18:14
This is a duplicate of #169 -- please add your discussion there.

**Closed** 2021-05-21 18:16 UTC

**Comment by jakearchibald** [comment] 2021-05-21 18:41
Hah, sorry, I searched for "mimetype" but it doesn't appear in that issue
