### ISSUE TITLE
How to properly copy and restore AudioData?

### ISSUE THREAD

**Issue by onthegit** [w3c/webcodecs#502] opened 2022-06-28 10:20 UTC
I use the following code to copy and restore the audio data from webcodecs, but it does not seem to properly work (audio is getting garbled, while the encoder accepts the copied audio data):

Code for copying the audio data:
```javascript
     const buffers = new Array<ArrayBuffer>(data.numberOfChannels)

        for (let i = 0; i < data.numberOfChannels; i++) {
          buffers[i] = new ArrayBuffer(data.allocationSize({
            planeIndex: i,
          }))
          data.copyTo(buffers[i], {
            planeIndex: i,
          })
        }
        const adConfig = {
          buffers: buffers,
          numberOfChannels: data.numberOfChannels,
          numberOfFrames: data.numberOfFrames,
          sampleRate: data.sampleRate,
          duration: data.duration,
          format: data.format,
          timestamp: data.timestamp
        }
        data.close()
```
Code for constructing the AudioData
```javascript
     const databuf = concatBuffers(adConfig.buffers)
     const ad = new AudioData({
            data: databuf,
            format: adConfig.format,
            numberOfChannels:adConfig.numberOfChannels,
            numberOfFrames: adConfig.numberOfFrames,
            timestamp: adConfig.timestamp,
            sampleRate: adConfig.sampleRate,
          })

    const concatBuffers = (buffers: ArrayBuffer[]) => {
        const len = buffers.reduce((a, b) => a + b.byteLength, 0)
        const ret = new Uint8Array(len);

        let offset = 0

        for (let i = 0; i < buffers.length; i++) {
          ret.set(new Uint8Array(buffers[i]), offset);
          offset += buffers[i].byteLength
        }

        return ret.buffer;
      }
```

**Comment by tguilbert-google** [comment] 2022-06-28 18:14
What is the value of `data.format` and `data.numberOfChannels`? I'm assuming it's a planar format, otherwise the code would fail at getting `planeIndex : i` for more than one channel.

Does audio also get garbled if you drop all but the first channel when reconstructing the AudioData?

Do you happen to have a full example page hosted somewhere? I can build a page myself otherwise.

**Comment by tguilbert-google** [comment] 2022-06-28 21:17
For the record, I don't see anything inherently wrong with the code snippets provided. If there is truly an issue, this would be a Chromium bug, which should probably be tracked on crbug.com. 

> `Failed to construct 'AudioData': data is too small: needs 8192 bytes, received 4096.`

If the other channels are dropped, the new `AudioData` constructor should be:
<pre>
     const ad = new AudioData({
            data: databuf,
            format: adConfig.format,
            <b>numberOfChannels: 1,</b>
            numberOfFrames: adConfig.numberOfFrames,
            timestamp: adConfig.timestamp,
            sampleRate: adConfig.sampleRate,
          })
</pre>

Garbling had me worried about interlacing/de-interlacing the audio during the copy. However, remaining in `f32-planar` should not cause such issues.

If there are no audio artifacts per-se but it is a sync issue, there might be something else going on. The difference in duration between the original and the reconstructed AudioData is surprising to me, since duration should be derived from `numberOfFrames` and `sampleRate`.

How are you playing out the audio and the video?

**Comment by onthegit** [comment] 2022-06-28 22:58
> For the record, I don't see anything inherently wrong with the code snippets provided. If there is truly an issue, this would be a Chromium bug, which should probably be tracked on crbug.com.
> 
> > `Failed to construct 'AudioData': data is too small: needs 8192 bytes, received 4096.`
> 
> If the other channels are dropped, the new `AudioData` constructor should be:
> 
>      const ad = new AudioData({
>             data: databuf,
>             format: adConfig.format,
>             numberOfChannels: 1,
>             numberOfFrames: adConfig.numberOfFrames,
>             timestamp: adConfig.timestamp,
>             sampleRate: adConfig.sampleRate,
>           })
> Garbling had me worried about interlacing/de-interlacing the audio during the copy. However, remaining in `f32-planar` should not cause such issues.
> 
> If there are no audio artifacts per-se but it is a sync issue, there might be something else going on. The difference in duration between the original and the reconstructed AudioData is surprising to me, since duration should be derived from `numberOfFrames` and `sampleRate`.
> 
> How are you playing out the audio and the video?

It turns out I had a problem with the timstamps. Here is what I do:
I get the audio and video chunks for different time ranges, lets say 2-5 and 15-20.
When I encode the audio chunks the timestamp is carried over from the decoder. Instead the timestamp should be continious because the resulting video will play from 2-5 and from 15-20 with total duration of 8 seconds, however because I dont know how to calculate before hand the duration of the AudioData I supply as well as the timestamp it messes the resulting video. For videoFrame I can set the duration, however for audiodata I can not, 
You said that audio duration is calculated based off of the number of frames. How to calculate the duration and therefore the next timestamp of the audio?

**Comment by tguilbert-google** [comment] 2022-06-28 23:45
> How to calculate the duration and therefore the next timestamp of the audio

`audioData.duration` in microseconds is `audioData.numberOfFrames / audioData.sampleRate * 1 000 000`, as per [the spec](https://w3c.github.io/webcodecs/#dom-audiodata-duration).

> Maybe I can recopy the data with copyTo() and change the next timestamp based on the duration of the audio?

Yes. If you are re-encoding discontinuous video chunks, you can rebase the matching AudioData timestamps (e.g., tracking the total number of audio frames sent to the audio encoder and calculating new timestamps yourself).

Keep in mind that you can also vary the number of audio frames used to initialize AudioData, or only copy out the frames you need with `copyTo({planeIndex : ..., frameOffset : ..., frameCount: ...})` ([spec](https://w3c.github.io/webcodecs/#audiodata-copy-to-options)).

Since your issue seems to be with your application code, and not with the WebCodecs API or Chromium's implementation of the API, I am closing this issue. If you run into unexpected behavior with Chromium's audio encoders, you can open an issue at [crbug.com](https://crbug.com).

**Closed by tguilbert-google** 2022-06-28 23:45 UTC

**Comment by onthegit** [comment] 2022-06-28 23:47
@tguilbert-google  thanks for everything.

**Comment by tguilbert-google** [comment] 2022-06-28 23:51
My pleasure!

I do note that copying out the data only to create a new AudioData with a different timestamp is inefficient. I think there was some discussion on how to update metadata other than by re-constructing an object, but I don't know where this landed. I will look for the issue and report back.

**Comment by onthegit** [comment] 2022-06-29 15:57
Now by manually calculating the timestamp before the audio is encoded (still there is descrepancy with duration at 60000 instead of 21333 emitted by the Encoder), the video and audio are more in sync, however, there are artefacts in the audio and Chrome is complaining:
```
Large timestamp gap detected; may cause AV sync to drift. time:15103000us expected:15180000us delta:-77000us

Maybe related somehow to : https://bugs.chromium.org/p/chromium/issues/detail?id=1254496 ?
```

**Comment by tguilbert-google** [comment] 2022-06-29 20:59
If an encoder does not have sufficient frames to emit a full chunk, it might pad the chunk data with silence (increasing the duration).

For now, the Chromium Opus encoder is configured to emit 60ms chunks, but we will revisit/improve this as per #371.

I don't think you need to copy/rebuffer the chunks yourself before feeding them in. The encoder should use an internal FIFO and take care of that for you. Make sure to not flush the encoder until you've fed all the frames into it.

**Comment by tguilbert-google** [comment] 2022-06-29 23:50
> I do note that copying out the data only to create a new AudioData with a different timestamp is inefficient. I think there was some discussion on how to update metadata other than by re-constructing an object, but I don't know where this landed. I will look for the issue and report back.

I've opened #505 to track this.

**Comment by onthegit** [comment] 2022-06-30 10:54
@tguilbert-google  Thanks again! I managed to make it working, the problem was flushing the audio encoder before all frames were sent, but will it overload the encoder if frames are sent in fast intervals for longer periods of time?

**Comment by tguilbert-google** [comment] 2022-06-30 19:54
It shouldn't. Let us know if it does though.

**Comment by sandersdan** [comment] 2022-06-30 20:10
> but will it overload the encoder if frames are sent in fast intervals for longer periods of time without flushing?

If you're doing faster-than-realtime processing, you should monitor the `encodeQueueSize` to avoid allocating large amounts of memory to buffering. For realtime processing it's unlikely for an audio encoder to become bogged down, but if that were to happen the only option is to reduce the complexity (fewer channels, lower sample rate, etc.).

`flush()` primarily notifies the encoder that no addition input is necessarily forthcoming. For audio this doesn't usually make any difference since audio codecs are typically keyframe-only (there are exceptions to that). `flush()` also provides notification of when the matching output is complete, which can be relevant in non-realtime situations.

**Comment by tiuvi** [comment] 2024-07-05 08:01
I am using the web codec to process audio and video both in real time and from disk.

I think audiodata does not need planeindex required but optional, in case the user wants the buffer just to store it.

https://developer.mozilla.org/en-US/docs/Web/API/AudioData/copyTo

In my case this is what I had to do to achieve it and thanks to this example because I had no idea about audio buffers.

```
    function pipeAudioStream(args) {

        const { audioTrack, audioEncoder, processFromDisk } = args;

        if (audioTrack === null) {
            return (new Promise((resolve) => { resolve(true) }));
        }

        const queuingStrategy = new CountQueuingStrategy({ highWaterMark: 1024 });

        return (new Promise(async (resolve) => {

            const cacheHandle = processFromDisk ? await caches.open(systemNameCache) : () => { };

            const writableStreamAudio = new WritableStream({
                //start(controller) {},
                async write(frame, controller) {

                    try {

                        if (processFromDisk) {

                            // Calcular la longitud total directamente y copiar los datos en una sola pasada
                            const concatenatedArray = new Uint8Array(frame.numberOfChannels * frame.allocationSize({ planeIndex: 0 }));

                            let offset = 0;
                            for (let i = 0; i < frame.numberOfChannels; i++) {

                                const buffer = new ArrayBuffer(frame.allocationSize({ planeIndex: i }));

                                frame.copyTo(buffer, { planeIndex: i });

                                const uint8Array = new Uint8Array(buffer);

                                concatenatedArray.set(uint8Array, offset);

                                offset += uint8Array.byteLength;

                            }

                            const buffer = concatenatedArray.buffer;

                            const blob = new Blob([buffer], { type: 'application/octet-stream' });

                            const urlWithTimestamp = `https://tiuvi.com/${systemNameCache}/frameaudio=${new Date().getTime()}`;

                            await cacheHandle.put(urlWithTimestamp, new Response(blob, {
                                status: 200,
                                statusText: 'OK',
                                headers: {
                                    "Content-Length": buffer.length,
                                    'Content-Type': 'application/octet-stream',
                                }
                            }));

                            audioframes.push({
                                format: frame.format,
                                duration: frame.duration,
                                timestamp: frame.timestamp,
                                sampleRate: frame.sampleRate,
                                numberOfFrames: frame.numberOfFrames,
                                numberOfChannels: frame.numberOfChannels,
                                urlOFline: urlWithTimestamp,
                            });

                            frame.close();

                            return
                        }

                        await audioEncoder.encode(dataframe);

                    } catch (error) {

                        audioEncoder.close();

                        onErrorMessage(onError, error);
                    }

                },
                //async close() {},
                abort(reason) {
                    // Lógica para manejar la cancelación del WritableStream
                    resolve({ err: reason });
                },
            }, queuingStrategy);

            await audioTrack.pipeTo(writableStreamAudio);

            resolve({ err: null });

        }));

    }
    
    
    //From here I get the frames from the cache again
              const cacheHandle = await caches.open(systemNameCache);


                for (const frameOptions of audioframes) {

                    try {

                        const { urlOFline, ...others } = frameOptions

                        const response = await cacheHandle.match(urlOFline);

                        const arrayBuffer = await response.arrayBuffer();

                        const reconstructedByteArray = new Uint8Array(arrayBuffer);

                        const frame = new AudioData({ data: reconstructedByteArray, ...others })

                        await audioEncoder.encode(frame);

                    } catch (error) {
                        console.log(error);
                        audioEncoder.close();

                        onErrorMessage(onError, error);
                    }
                }
                
                
             If I could obtain the buffer directly it would be much more efficient and faster.
