### ISSUE TITLE
VideoDecoder and Intra Refresh?

### ISSUE THREAD

**Issue by warvstar** [w3c/webcodecs#710] opened 2023-08-21 15:47 UTC
Is it possible to decode an h264 or AV1 stream with intra refresh instead of I frames? When I switch to using intra refresh (through ffmpeg or nvenc) the decoder crashes as its expecting a keyframe.

**Comment by dalecurtis** [comment] 2023-08-21 16:52
I think this is a duplicate of #650.

@sandersdan

**Comment by sandersdan** [comment] 2023-08-21 17:07
Yes I believe this is the same request.

**Closed** 2023-08-21 17:08 UTC
