### ISSUE TITLE
VideoEncoder.configure bitrate has no effect.

### ISSUE THREAD

**Issue by yuyao1015** [w3c/webcodecs#430] opened 2021-12-31 08:16 UTC
Hi all,
I am using  webcodec for media recording. But the exported video file with an extremely low quality.

Here is my configure for VideoEncoder
```
        var vCfg = {
            bitrate: 10000000, // It seems has no effect for the quality of the encoded file
            codec: "avc1.42001E",
            height: 1080,
            width: 1920
        }
        const vr = await VideoEncoder.isConfigSupported(vCfg);
```

I also tryed other params such as 'framerate', 'bitrateMode', but they still has no effects.

But when i change the codec from "avc1...." to "vp9....", the exported file is large, It seem the quality may improved.(I mux it into mp4, so i can't play the file with codec of vp9 to check the quality).

Any suggest ? Thanks!

Update:
I test it in mac, but when it run it at windows, It seems has no problem.  It's theres some limits on macos ?

**Comment by ziyunfei** [comment] 2022-01-02 07:12
`        hardwareAcceleration: 'prefer-software',
`

**Comment by yuyao1015** [comment] 2022-01-05 02:21
> ` hardwareAcceleration: 'prefer-software',`

谢谢！It works!

**Comment by chcunningham** [comment] 2022-01-05 06:27
> I test it in mac, but when it run it at windows, It seems has no problem. It's theres some limits on macos ?

Sounds like a bug in Chrome's accelerate encoder on mac. @djuffin, is this a known issue?

**Comment by Djuffin** [comment] 2022-01-06 04:14
I can't reproduce this issue. I'm using  https://bitrate-compare.glitch.me/ and I can see actual bitrate being affected by the settings.

It produces configs that look like this:
{"codec":"avc1.42001E","hardwareAcceleration":"prefer-hardware","width":1280,"height":720,"bitrate":2000000,"bitrateMode":"constant","framerate":24,"latencyMode":"quality","avc":{"format":"annexb"}}

**Comment by ziyunfei** [comment] 2022-01-06 05:05
try `encoder.encode(new VideoFrame(src), { keyFrame: insert_keyframe })` in that glitch

**Comment by Djuffin** [comment] 2022-01-06 22:24
I think I know what seems to be the problem in your case. 
Your frames seems to be lacking timestamps and their absence deprives the encoder of a reliable signal for rate control.

Try something like this:
let frame = new VideoFrame(src, { timestamp: performance.now() * 1000 });

**Comment by yuyao1015** [comment] 2022-01-07 03:10
> 

Thanks a lot. It works!   The timestamp VideoDecoder generated it's a value related to the timescale, when I change it to a real value, it works well.

**Comment by chcunningham** [comment] 2022-01-07 03:47
Yay! We're [working on making it harder to create VideoFrame w/out timestamp](https://chromestatus.com/feature/5667793157488640). Sorry this bit you. 

Closing since it seems like this is all sorted. Feel free to reopen if more to discuss.

**Closed by chcunningham** 2022-01-07 03:47 UTC

**Comment by fyuvb** [comment] 2022-01-18 11:34
> I think I know what seems to be the problem in your case. Your frames seems to be lacking timestamps and their absence deprives the encoder of a reliable signal for rate control.
> 
> Try something like this: let frame = new VideoFrame(src, { timestamp: performance.now() * 1000 });

Hi I had the some problem. The bitrate could be controlled using prefer-software but it does not work under prefer-hardware. I was also using a Mac with Intel Core.

I tried adding timestamp in millisecond or in timescale and none worked. Could you elaborate how I could add timestamp to those frames? what is the "performance" in your context? 

@yuyao1015 could you advice as well? Thank you so much for your help!

**Comment by Djuffin** [comment] 2022-01-18 11:40
"performance" in this context refers to https://developer.mozilla.org/en-US/docs/Web/API/Performance/now

Timestamps should be in microseconds

**Comment by fyuvb** [comment] 2022-01-19 03:20
Thanks for the reply.
It turns out that if I changed the timestamp to microseconds it worked.
```
    const videoFrameDurationInMicrosecond = 1_000_000 / 30;
    const timestamp = videoFrameDurationInMicrosecond * frameIndex;
    const frame = new VideoFrame(bitmap, { timestamp, duration: videoFrameDurationInMicrosecond});
    videoEncoder.encode(frame)
```

**Comment by sandersdan** [comment] 2022-01-19 19:47
FYI we do intend to eventually log a warning for this mistake in Chrome, it's https://bugs.chromium.org/p/chromium/issues/detail?id=1199046.
