### ISSUE TITLE
Whether the video frame has reserved bytes ？

### ISSUE THREAD

**Issue by yangfangfang1204** [w3c/webcodecs#673] opened 2023-05-15 03:34 UTC
whether the webcodecs has reserved byes in input encodedVideoChunk ?
decode: Input the crop information of one video frame and transparently transmit the crop information in output .
such as:
(1) input:
const chunk = `new EncodedVideoChunk({
  data,
  timestamp,
  type,
  reserve:8,  // reserved bytes that we could transmit to output.
})`
decodeobj.decode(chunk);
(2) output
output(frame){
  let timestamp = frame.timestamp;
  let cropwidth = frame.reserver;
}

**Comment by padenot** [comment] 2023-05-15 09:23
This is a duplicate of https://github.com/w3c/webcodecs/issues/189. There is no way to do this right now, but it's not the first time this has been asked for.

**Closed by padenot** 2023-05-15 09:23 UTC
