### ISSUE TITLE
encoding h264 issue

### ISSUE THREAD

**Issue by Hellgin** [w3c/webcodecs#394] opened 2021-11-04 22:00 UTC
Hey, was wondering if I'm missing a step or if h264 encoding is just not supported by chrome yet.

h264 decodes just fine, vp8 decodes and encodes just fine, but If I change the codec string of my encoder's configuration from "vp8" (which works fine) to a h264 codec string (for example "avc1.4d001f") the entire browser tab crashes with a ACCESS_VIOLATION error. Is there extra steps involved in creating a h264 encoder? or is h264 encoding just not supported yet?

**Comment by sandersdan** [comment] 2021-11-04 22:04
H.264 encoding is supported in Chrome via OpenH264. An ACCESS_VIOLATION is quite severe, please file a bug with reproduction steps at https://bugs.chromium.org/p/chromium/issues/entry. If you post a link back here I can then make sure it gets routed correctly.

**Comment by aboba** [comment] 2021-11-04 22:16
@hellgin   No issue I can see with H.264 encode/decode either on Chrome Stable M95 or Canary.

If you're looking for a sample app to play around, encoding/decoding various resolutions with hardware preferences of your choosing, try this: https://webrtc.internaut.com/wc/wtSender/

(This requires you to set the "Experimental" flag in chrome://flags since it also tests the WebTransport API).

**Comment by Hellgin** [comment] 2021-11-04 23:08
@aboba Hi, Thank you for confirming that H.264 should work, I looked a little deeper into my issue and discovered something. It only crashes when I have multiple 264 encoders encoding at the same time and only if I use main or high profile (baseline has no issue). My app reads from a Video track and encodes it to multiple resolutions, by default there will be more than one resolution but If I force it to only use one output resolution (so only one encoder) h264 encoding works without issue. I adjusted the frame rate and it makes no difference, I can have 1 h264 encoder encoding at 60 frames per second but I cant have 2 of them encoding at 1 frame per second each. It will encode a couple of frames and then crash with a status access violation error each time.

I will try and create a condense reproducible example.

**Comment by dalecurtis** [comment] 2021-11-04 23:13
Just providing the crash id from chrome://crashes is useful to us if you can't make a reproducer.

**Comment by Hellgin** [comment] 2021-11-05 00:34
ok, I created a reproducer but in the process discovered that I don't close old encoders. I recreate video encoders to force new key frames (don't know if that's the best practice but it works), 

So now this issue only happens when all of the following criteria is met

a) you use main or high profile h264. 
b) you use multiple encoders at the same time. 
c) you recreate the encoders when you want to force a new keyframe. 
d) you don't close the old encoders before creating the new ones.

 I tested this snippet on chrome on my android and it worked just fine, meaning it's very likely related to the drivers/hardware on my pc

Here is the code to reproduce.

[test.txt](https://github.com/w3c/webcodecs/files/7479650/test.txt)

**Comment by Djuffin** [comment] 2021-11-05 00:51
Thanks for the repro, I'll take a look.

**Comment by Djuffin** [comment] 2021-11-05 02:06
I opened a Chromium bug to track this crash. https://crbug.com/1267085

**Comment by Djuffin** [comment] 2021-11-05 02:12
As a workaround I suggest closing encoders before creating new ones.
if (encoder1) encoder1.close();
if (encoder2) encoder2.close();

**Comment by Hellgin** [comment] 2021-11-05 06:32
Thank you

**Comment by Djuffin** [comment] 2022-06-28 02:33
This issue should be closed now

**Closed** 2022-06-28 19:05 UTC
Labels: Question
