### ISSUE TITLE
Metadata parsing for media files

### ISSUE THREAD

**Issue by AnthumChris** [w3c/webcodecs#411] opened 2021-11-23 20:43 UTC
Could WebCodecs provide us with an easy way to view metadata or stream information for binary media files (audio, video, image, etc)?  _(Related to https://github.com/w3c/webcodecs/issues/201)._ 

For example, it would be great to quickly parse and obtain the metadata for a binary audio file like Opus or MP3 to know the bit depth, sample rate, number of channels, etc.  After researching StackOverflow question ["How to get [metadata] with Web Audio API?"](https://stackoverflow.com/questions/70071519/how-to-get-sample-rate-bit-depth-and-number-of-channels-with-web-audio-api), I was unable to find an existing solution to obtain metadata without requiring developers to manually parse the binary file headers.

Command-line codec tools currently provide a wealth of metadata information:
1. [`opusinfo`](https://opus-codec.org/docs/opus-tools/opusinfo.html) - [Opus screenshot](https://user-images.githubusercontent.com/10064176/143101229-85863522-36a9-431f-bc03-d8aff25cb599.png)
2. [`ffmpeg`](https://www.ffmpeg.org/ffmpeg.html) - [MP3 screenshot](https://user-images.githubusercontent.com/10064176/143107182-fa249a4a-e555-49a9-b670-4014998d6ae0.png), [Opus screenshot](https://user-images.githubusercontent.com/10064176/143108089-c0986947-37a6-4f87-a0d8-33219a0584b0.png)

**Comment by sandersdan** [comment] 2021-11-29 20:10
Duplicate of #24.

**Closed by sandersdan** 2021-11-29 20:10 UTC
